### ISSUE TITLE
Invitación

### ISSUE THREAD

**Issue by pedroprieto** [magarciaes2022/prueba-github#6]
Hola, @magarciaes2022 

La invitación no la tienes que hacer para un repositorio, sino para una organización que debes crear.

Un saludo!

**Comment by magarciaes2022** [comment]
hola Pedro,

Pillada!!

resulta que estoy siguiendo tus apuntes y videos, y voy haciendo pruebas.

No estoy haciendo aún la tarea.

Disculpa que te haya llegado la invitación.



Mª Ángeles García Escrig

Profesora del Departamento de Informática

IES Camp de Morvedre

Avda. Fausto Caruana S/N, 46520 Sagunto, Valencia

962 617 724| ***@***.***

www.iescamp.es<http://www.iescamp.es/>

________________________________
De: Pedro Prieto ***@***.***>
Enviado: lunes, 4 de abril de 2022 16:58
Para: magarciaes2022/prueba-github ***@***.***>
Cc: GARCIA ESCRIG, MARIA ANGELES ***@***.***>; Mention ***@***.***>
Asunto: [magarciaes2022/prueba-github] Invitación (Issue #6)


Hola, @magarciaes2022<https://github.com/magarciaes2022>

La invitación no la tienes que hacer para un repositorio, sino para una organización que debes crear.

Un saludo!

**Comment by pedroprieto** [comment]
Ah, perfecto!! Sin problema!! 😉
